Name: "Nimbus Sample Environment"

Commands:
    - sudo apt-get update
    - sudo apt-get install -y curl wget sudo gnupg nano net-tools openssh-server git neofetch tree zsh apt-transport-https ca-certificates build-essential gh chromium postgresql-13
